version: '3.1'

services:
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
volumes:
    postgresql:
    postgresql_data:
networks:
  default:
    name: stockmanager-infra_default  