version: '3.1'

services:
    sonarqube:
        image: sonarqube
        ports:
            - 9000:9000
        environment:
            - sonar.jdbc.url=jdbc:postgresql://wsl.local:5432/sonar
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
networks:
  default:
    external:
      name: stockmanager-infra_default